[build]
base = "./app"
command = "npm run build"
publish = "out"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' bsky.social public.api.bsky.app; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: *.bsky.social cdn.bsky.app; font-src 'self' data:;"

# Handle client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Force HTTPS
[[redirects]]
from = "http://*"
to = "https://:splat"
status = 301
force = true
