name: oxlint
on:
    push:
        branches: [main]
        paths:
            - "app/**"
            - ".github/workflows/oxlint.yml"
    pull_request:
        branches: [main]
        paths:
            - "app/**"
            - ".github/workflows/oxlint.yml"

jobs:
    oxlint:
        name: Lint JS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npx --yes oxlint@latest --deny-warnings # change to the latest release
